ALTER TABLE `users` ADD COLUMN `auth0_sub` VARCHAR(255) UNIQUE COMMENT 'Auth0 User ID' AFTER `id`;
ALTER TABLE `users` MODIFY COLUMN `password` VARCHAR(128) NULL COMMENT 'パスワード';
ALTER TABLE `users` MODIFY COLUMN `token` VARCHAR(128) NULL COMMENT '認証用Token';
ALTER TABLE `users` MODIFY COLUMN `code` VARCHAR(10) NULL COMMENT 'ワンタイムパスワード';
