ALTER TABLE `users` DROP COLUMN `auth0_sub`;
ALTER TABLE `users` MODIFY COLUMN `password` VARCHAR(128) NOT NULL COMMENT 'パスワード';
ALTER TABLE `users` MODIFY COLUMN `token` VARCHAR(128) NOT NULL COMMENT '認証用Token';
ALTER TABLE `users` MODIFY COLUMN `code` VARCHAR(10) NOT NULL COMMENT 'ワンタイムパスワード';
